-- FoodLens database schema (Supabase / Postgres) — documentation of the live
-- database. Every statement is idempotent, so the file is safe to re-run on a
-- fresh project or on the existing one.

-- ── Tables ───────────────────────────────────────────────────────────────────
create table if not exists public.meals (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null default auth.uid()
                  references auth.users (id) on delete cascade,
  meal_type       text check (meal_type = any (array['breakfast', 'lunch', 'dinner', 'snack'])),
  eaten_at        timestamptz not null default now(),
  total_kcal      numeric not null default 0,
  total_protein_g numeric not null default 0,
  total_carbs_g   numeric not null default 0,
  total_fat_g     numeric not null default 0
);

create table if not exists public.meal_items (
  id             bigint generated by default as identity primary key,
  meal_id        bigint not null references public.meals (id) on delete cascade,
  food_class     text not null,
  quantity       integer not null default 1 check (quantity >= 1),
  grams_per_item numeric not null check (grams_per_item > 0),
  confidence     numeric check (confidence >= 0 and confidence <= 1),
  kcal           numeric not null,
  protein_g      numeric not null,
  carbs_g        numeric not null,
  fat_g          numeric not null
);

-- The USDA record description an item's nutrition came from, or 'fallback'
-- for the built-in table. Nullable: rows saved before it existed have none.
alter table public.meal_items add column if not exists nutrition_source text;

-- One row of daily targets per user. NOT YET CONFIRMED against the database:
-- the column names are verified, but the types, the key and the policy below
-- are inferred, because they can't be read without the secret key.
create table if not exists public.goals (
  user_id         uuid primary key default auth.uid()
                  references auth.users (id) on delete cascade,
  daily_kcal      numeric,
  daily_protein_g numeric,
  daily_carbs_g   numeric,
  daily_fat_g     numeric,
  updated_at      timestamptz not null default now()
);

-- History reads one user's meals by date; Postgres doesn't index foreign keys.
create index if not exists meals_user_time_idx on public.meals (user_id, eaten_at desc);
create index if not exists meal_items_meal_idx on public.meal_items (meal_id);

-- ── Row-level security: each user sees and writes only their own rows ────────
alter table public.meals      enable row level security;
alter table public.meal_items enable row level security;
alter table public.goals      enable row level security;

drop policy if exists "own meals" on public.meals;
create policy "own meals" on public.meals
  for all to authenticated
  using      ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "own meal items" on public.meal_items;
create policy "own meal items" on public.meal_items
  for all to authenticated
  using (exists (select 1 from public.meals m
                 where m.id = meal_items.meal_id and m.user_id = (select auth.uid())))
  with check (exists (select 1 from public.meals m
                      where m.id = meal_items.meal_id and m.user_id = (select auth.uid())));

-- Inferred, see the note on public.goals.
drop policy if exists "own goals" on public.goals;
create policy "own goals" on public.goals
  for all to authenticated
  using      ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- ── save_meal: a meal and all its items in one transaction ───────────────────
-- SECURITY INVOKER, so both inserts run as the caller and RLS applies.
create or replace function public.save_meal(p_meal_type text, p_items jsonb)
returns public.meals
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_meal public.meals;
begin
  if auth.uid() is null then
    raise exception 'Not logged in' using errcode = '42501';
  end if;
  if p_meal_type is null then
    raise exception 'A meal type is required' using errcode = '22023';
  end if;
  if jsonb_typeof(p_items) is distinct from 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'A meal needs at least one item' using errcode = '22023';
  end if;

  -- user_id and eaten_at come from the column defaults (auth.uid(), now());
  -- totals are summed from the items, so the two can never disagree.
  insert into public.meals (meal_type, total_kcal, total_protein_g, total_carbs_g, total_fat_g)
  select p_meal_type, sum(i.kcal), sum(i.protein_g), sum(i.carbs_g), sum(i.fat_g)
  from jsonb_populate_recordset(null::public.meal_items, p_items) as i
  returning * into v_meal;

  insert into public.meal_items
    (meal_id, food_class, quantity, grams_per_item, confidence,
     kcal, protein_g, carbs_g, fat_g, nutrition_source)
  select v_meal.id, i.food_class, i.quantity, i.grams_per_item, i.confidence,
         i.kcal, i.protein_g, i.carbs_g, i.fat_g, i.nutrition_source
  from jsonb_populate_recordset(null::public.meal_items, p_items) as i;

  return v_meal;
end;
$$;

revoke execute on function public.save_meal(text, jsonb) from public, anon;
grant  execute on function public.save_meal(text, jsonb) to authenticated;
